
# Required: A short name for the action package
name: Local computer folder to ChatGPT
    
# Required: A description of what's in the action package.
description: This is made only for demonstrating the power of Python actions when used with ChatGPT, not for production usage.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/desktop-files/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  pypi:
  - sema4ai-actions=0.3.1
  - rpaframework=28.5.1

